name: bb2_mobile_app
description: A BB2 admin mobile app for ReBBL.
publish_to: none

version: 1.0.3+10

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  BB2Admin:
    git: https://github.com/mjbader/bb2-net-client.git

  cupertino_icons: ^1.0.4

  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.9
  flutter_sticky_header: ^0.6.0
  flutter_platform_widgets: ^1.11.1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/